### ISSUE TITLE
Wikis belonging public repos are not available

### ISSUE THREAD

**Issue by bartkamphorst** [repotag/repotag#5]
Mounting of the wikis is done for authenticated users only. However, public repos should have public wikis.

**Comment by dometto** [comment]
Good point. Maybe it's a good idea to write some routing specs for the wikis and for grack first. BDD seems like a sensible strategy here. :)

**Comment by dometto** [comment]
Do we want public wikis to be publicly editable? If not, do we want to stay to same roles/abilities as for ordinary repos? I can imagine you have a repo, and you want some users (watchers on the repo) to be able to edit the corresponding wiki, but not the repo itself. But then authorization would get more complicated: abilities on repos and wikis wouldnt map 1-to-1.

**Comment by dometto** [comment]
The whole issue of wiki routing and authorization turns out not be so simple. If we want role management for wikis, it would have to be a separate model, so we can use cancancan to authorize it. Then there needs to be a wiki settings page on which you can add collaborators, etc.

The simplest option is just to serve every repository as a wiki under /wiki/user/repository, with authorization simply the same as for the route /user/repository. This could be prevented with a 'dont serve wiki' setting for repositories. The drawback in that case is that if you want a project with a separate wiki, you would need to manage two different repos. Unless we think of a way to have wiki's inherit authorization from a repository---but then we would have to make it a separate model that `belongs_to` a `Repository` again.

Another option is to use gollum's `--page-file-dir` so you could at least keep the wiki in a separate subdirectory of a repository.

**Comment by dometto** [comment]
Authorization for wikis (including public etc.) is now transparently handled in `ability.rb`.
